This is an introduction to evolutionary computation in Python with NumPy.

In [10]:
import numpy as np

In [11]:
def sphere(value):
    return np.dot(value.T, value)

In [12]:
N = 5
x = 2 * np.ones(N)

In [13]:
f = sphere(x)

In [16]:
g = 0

fitness = sphere(x)
sigma = 1.

while g < 100:
    g += 1

    x_ = x + sigma * np.random.randn(N)
    fitness_ = sphere(x_)

    if fitness_ <= fitness:
        x = x_
        fitness = fitness_

    print("In generation", g, "we have a fitness of:", fitness)

[-0.53080103  0.63470729  0.13182569 -0.76040887  2.02813143]
[-0.00140143  1.23359592  0.831521   -0.68175403  0.5793734 ]
In generation 1 we have a fitness of: 0.4326293085582745
[ 0.04584349  1.41932425 -0.96908654  0.16321942 -0.20772535]
[ 2.77933975  0.18810972  0.41400531  0.60363275 -0.21813922]
In generation 2 we have a fitness of: 0.4326293085582745
[-2.21765112 -0.07660524  0.98596789 -0.41170597 -0.2555218 ]
[ 0.68018094 -0.89938472  1.05708885  0.38231076  0.30675   ]
In generation 3 we have a fitness of: 0.4326293085582745
[-1.24772526  0.36540034 -0.99828983  0.37902211  0.75089521]
[ 0.75717855  0.28618421  1.0360682  -0.23463076 -0.85888579]
In generation 4 we have a fitness of: 0.4326293085582745
[-0.56263891  0.1700256   1.68714558  0.17082776 -0.88045987]
[0.55180287 0.9320634  1.34890218 0.88367949 1.09943171]
In generation 5 we have a fitness of: 0.4326293085582745
[-0.60337492  0.62308268 -0.30970179 -0.33400264 -0.15959959]
[-1.09819806  1.0383596   1.20796246  